#!/bin/sh
# script/bootstrap: Resolve dependencies that the application requires to run.

# Exit if any subcommand fails
set -e

if [[ -z "${INPUT_directory}" ]]; then
  # No input directory provided
  cd "$(dirname "$0")/.."
else
  cd "${INPUT_directory}"
fi

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi
